param(
    [Parameter(Mandatory = $true)][string]$PublicIp,
    [Parameter(Mandatory = $true)][string]$RelayDomain,
    [Parameter(Mandatory = $true)][string]$LiveKitDomain
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path $PSScriptRoot -Parent
$envPath = Join-Path $repoRoot ".env"

if (Test-Path -LiteralPath $envPath) {
    throw ".env already exists. Refusing to overwrite deployment secrets."
}

$parsedIp = $null
if (-not [System.Net.IPAddress]::TryParse($PublicIp, [ref]$parsedIp)) {
    throw "PublicIp must be a valid public IPv4 or IPv6 address."
}

$domainPattern = '^(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,63}$'
if ($RelayDomain -notmatch $domainPattern -or $LiveKitDomain -notmatch $domainPattern) {
    throw "RelayDomain and LiveKitDomain must be fully qualified domain names."
}

function New-UrlSafeSecret([int]$ByteCount) {
    $bytes = New-Object byte[] $ByteCount
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $generator.GetBytes($bytes) } finally { $generator.Dispose() }
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

$databasePassword = New-UrlSafeSecret 36
$liveKitApiKey = "omnirelay-" + (New-UrlSafeSecret 9).ToLowerInvariant()
$liveKitApiSecret = New-UrlSafeSecret 48
$turnSharedSecret = New-UrlSafeSecret 48

$lines = @(
    "# Generated by deploy/initialize-production.ps1. Never commit this file.",
    "POSTGRES_PASSWORD=$databasePassword",
    "LIVEKIT_API_KEY=$liveKitApiKey",
    "LIVEKIT_API_SECRET=$liveKitApiSecret",
    "TURN_SHARED_SECRET=$turnSharedSecret",
    "TURN_REALM=$LiveKitDomain",
    "PUBLIC_HOST=$PublicIp",
    "LIVEKIT_PUBLIC_URL=wss://$LiveKitDomain",
    "BACKEND_PORT=8080",
    "BACKEND_BIND_ADDRESS=127.0.0.1",
    "LIVEKIT_HTTP_BIND_ADDRESS=127.0.0.1",
    "TRUST_PROXY=true",
    "RELAY_DOMAIN=$RelayDomain",
    "LIVEKIT_DOMAIN=$LiveKitDomain",
    "FIREBASE_SERVICE_ACCOUNT_JSON="
)

[System.IO.File]::WriteAllLines(
    $envPath,
    $lines,
    (New-Object System.Text.UTF8Encoding($false))
)
& (Join-Path $PSScriptRoot "render-config.ps1") `
    -PublicHost $PublicIp `
    -LiveKitApiKey $liveKitApiKey `
    -LiveKitApiSecret $liveKitApiSecret `
    -TurnSharedSecret $turnSharedSecret | Out-Null

Write-Output "Created ignored .env and deploy/livekit.generated.yaml."
Write-Output "Add FIREBASE_SERVICE_ACCOUNT_JSON to .env when FCM is ready, then run deploy/start-production.ps1."
