param(
    [string]$HostAddress,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path $PSScriptRoot -Parent
$envPath = Join-Path $repoRoot ".env"

if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
    throw ".env already exists. Use -Force only when intentionally rotating local secrets."
}

if ([string]::IsNullOrWhiteSpace($HostAddress)) {
    $defaultRoute = Get-NetRoute -DestinationPrefix "0.0.0.0/0" -ErrorAction SilentlyContinue |
        Where-Object { $_.NextHop -ne "0.0.0.0" } |
        Sort-Object RouteMetric, InterfaceMetric |
        Select-Object -First 1
    if ($null -eq $defaultRoute) {
        throw "Could not detect a LAN address. Pass -HostAddress explicitly."
    }
    $HostAddress = Get-NetIPAddress `
        -InterfaceIndex $defaultRoute.InterfaceIndex `
        -AddressFamily IPv4 `
        -ErrorAction SilentlyContinue |
        Where-Object { $_.IPAddress -notlike "169.254.*" } |
        Select-Object -ExpandProperty IPAddress -First 1
}

$parsedAddress = $null
if (-not [System.Net.IPAddress]::TryParse($HostAddress, [ref]$parsedAddress) -or
    $parsedAddress.AddressFamily -ne [System.Net.Sockets.AddressFamily]::InterNetwork) {
    throw "HostAddress must be a valid IPv4 address reachable by the test devices."
}

function New-UrlSafeSecret([int]$ByteCount) {
    $bytes = New-Object byte[] $ByteCount
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $generator.GetBytes($bytes) } finally { $generator.Dispose() }
    return [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

$liveKitApiKey = "omnirelay-local-" + (New-UrlSafeSecret 9).ToLowerInvariant()
$liveKitApiSecret = New-UrlSafeSecret 48
$turnSharedSecret = New-UrlSafeSecret 48

$lines = @(
    "# Generated by deploy/initialize-local.ps1. Never commit this file.",
    "# Reachable on the local network at $HostAddress.",
    "DATABASE_URL=",
    "DATABASE_MIGRATION_URL=",
    "DATABASE_POOL_MAX=4",
    "DATABASE_POOL_IDLE_TIMEOUT_MS=30000",
    "DATABASE_CONNECTION_TIMEOUT_MS=5000",
    "DATABASE_QUERY_TIMEOUT_MS=12000",
    "DATABASE_STATEMENT_TIMEOUT_MS=10000",
    "DATABASE_POOL_MAX_USES=5000",
    "HTTP_REQUEST_TIMEOUT_MS=15000",
    "MAX_IN_FLIGHT_REQUESTS=64",
    "HTTP_MAX_CONNECTIONS=768",
    "WEBSOCKET_MAX_CONNECTIONS=512",
    "PUSH_MAX_CONCURRENCY=4",
    "PUSH_MAX_QUEUED=256",
    "SHUTDOWN_TIMEOUT_MS=25000",
    "CLEANUP_INTERVAL_SECONDS=900",
    "CLEANUP_BATCH_SIZE=500",
    "CALL_SIGNAL_TTL_SECONDS=60",
    "CALL_MAX_FUTURE_SKEW_SECONDS=15",
    "CALL_ACTIVE_LEASE_SECONDS=120",
    "MAX_REGISTRATION_CHALLENGES_PER_DEVICE=4",
    "MAX_REGISTRATION_CHALLENGES_PER_ACCOUNT=16",
    "MAX_MAILBOX_MESSAGES=10000",
    "MAX_PENDING_MESSAGES_PER_PAIR=100",
    "LIVEKIT_API_KEY=$liveKitApiKey",
    "LIVEKIT_API_SECRET=$liveKitApiSecret",
    "TURN_SHARED_SECRET=$turnSharedSecret",
    "TURN_REALM=omnirelay.local",
    "TURN_BIND_ADDRESS=0.0.0.0",
    "PUBLIC_HOST=$HostAddress",
    "LIVEKIT_PUBLIC_URL=ws://${HostAddress}:7880",
    "BACKEND_PORT=8080",
    "BACKEND_BIND_ADDRESS=0.0.0.0",
    "LIVEKIT_HTTP_BIND_ADDRESS=0.0.0.0",
    "TRUST_PROXY=false",
    "RELAY_DOMAIN=relay.localhost",
    "LIVEKIT_DOMAIN=livekit.localhost",
    "FIREBASE_PROJECT_ID=omnirelay-a3f00",
    "GOOGLE_APPLICATION_CREDENTIALS=",
    "FIREBASE_SERVICE_ACCOUNT_JSON="
)

[System.IO.File]::WriteAllLines(
    $envPath,
    $lines,
    (New-Object System.Text.UTF8Encoding($false))
)

& (Join-Path $PSScriptRoot "render-config.ps1") `
    -PublicHost $HostAddress `
    -NodeIp $HostAddress `
    -UseExternalIp $false `
    -LiveKitApiKey $liveKitApiKey `
    -LiveKitApiSecret $liveKitApiSecret `
    -TurnSharedSecret $turnSharedSecret | Out-Null

Write-Output "Created ignored .env and deploy/livekit.generated.yaml for $HostAddress."
Write-Output "Run deploy/configure-neon.ps1, then deploy/start-local.ps1."
