param(
    [Parameter(Mandatory = $true)][string]$PublicIp,
    [Parameter(Mandatory = $true)][string]$RelayDomain,
    [Parameter(Mandatory = $true)][string]$LiveKitDomain
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path $PSScriptRoot -Parent
$envPath = Join-Path $repoRoot ".env"

if (Test-Path -LiteralPath $envPath) {
    throw ".env already exists. Refusing to overwrite deployment secrets."
}

$parsedIp = $null
if (-not [System.Net.IPAddress]::TryParse($PublicIp, [ref]$parsedIp)) {
    throw "PublicIp must be a valid public IPv4 or IPv6 address."
}

$domainPattern = '^(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,63}$'
if ($RelayDomain -notmatch $domainPattern -or $LiveKitDomain -notmatch $domainPattern) {
    throw "RelayDomain and LiveKitDomain must be fully qualified domain names."
}

function New-UrlSafeSecret([int]$ByteCount) {
    $bytes = New-Object byte[] $ByteCount
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $generator.GetBytes($bytes) } finally { $generator.Dispose() }
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

$databasePassword = New-UrlSafeSecret 36
$liveKitApiKey = "omnirelay-" + (New-UrlSafeSecret 9).ToLowerInvariant()
$liveKitApiSecret = New-UrlSafeSecret 48
$turnSharedSecret = New-UrlSafeSecret 48

$lines = @(
    "# Generated by deploy/initialize-production.ps1. Never commit this file.",
    "POSTGRES_PASSWORD=$databasePassword",
    "DATABASE_POOL_MAX=4",
    "DATABASE_POOL_IDLE_TIMEOUT_MS=30000",
    "DATABASE_CONNECTION_TIMEOUT_MS=5000",
    "DATABASE_QUERY_TIMEOUT_MS=12000",
    "DATABASE_STATEMENT_TIMEOUT_MS=10000",
    "DATABASE_POOL_MAX_USES=5000",
    "HTTP_REQUEST_TIMEOUT_MS=15000",
    "MAX_IN_FLIGHT_REQUESTS=64",
    "HTTP_MAX_CONNECTIONS=768",
    "WEBSOCKET_MAX_CONNECTIONS=512",
    "PUSH_MAX_CONCURRENCY=4",
    "PUSH_MAX_QUEUED=256",
    "SHUTDOWN_TIMEOUT_MS=25000",
    "CLEANUP_INTERVAL_SECONDS=900",
    "CLEANUP_BATCH_SIZE=500",
    "CALL_SIGNAL_TTL_SECONDS=60",
    "CALL_MAX_FUTURE_SKEW_SECONDS=15",
    "CALL_ACTIVE_LEASE_SECONDS=120",
    "MAX_REGISTRATION_CHALLENGES_PER_DEVICE=4",
    "MAX_MAILBOX_MESSAGES=10000",
    "MAX_PENDING_MESSAGES_PER_PAIR=100",
    "LIVEKIT_API_KEY=$liveKitApiKey",
    "LIVEKIT_API_SECRET=$liveKitApiSecret",
    "TURN_SHARED_SECRET=$turnSharedSecret",
    "TURN_REALM=$LiveKitDomain",
    "PUBLIC_HOST=$PublicIp",
    "LIVEKIT_PUBLIC_URL=wss://$LiveKitDomain",
    "BACKEND_PORT=8080",
    "BACKEND_BIND_ADDRESS=127.0.0.1",
    "LIVEKIT_HTTP_BIND_ADDRESS=127.0.0.1",
    "TRUST_PROXY=true",
    "RELAY_DOMAIN=$RelayDomain",
    "LIVEKIT_DOMAIN=$LiveKitDomain",
    "FIREBASE_SERVICE_ACCOUNT_JSON="
)

[System.IO.File]::WriteAllLines(
    $envPath,
    $lines,
    (New-Object System.Text.UTF8Encoding($false))
)
& (Join-Path $PSScriptRoot "render-config.ps1") `
    -PublicHost $PublicIp `
    -LiveKitApiKey $liveKitApiKey `
    -LiveKitApiSecret $liveKitApiSecret `
    -TurnSharedSecret $turnSharedSecret | Out-Null

Write-Output "Created ignored .env and deploy/livekit.generated.yaml."
Write-Output "Add FIREBASE_SERVICE_ACCOUNT_JSON to .env when FCM is ready, then run deploy/start-production.ps1."
